apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExtension
metadata:
  name: o11y-metrics
  finalizers:
    - extensions-finalizer.argocd.argoproj.io
spec:
  sources:
    - web:
        url: https://github.com/argoproj-labs/argocd-extension-metrics/raw/main/extensions/resource-metrics/resource-metrics-extention/ui/dist/extension.tar
        