apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExtension
metadata:
  name: argocd-metrics-ext
  labels:
    tab: "Metrics"
    icon: "fa-chart"
  finalizers:
    - extensions-finalizer.argocd.argoproj.io
spec:
  sources:
    - web:
        url: https://github.com/maheshopsmx/argocd-extension-metrics/releases/download/v0.0.4/extension.tar
