name: release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - dev-*

defaults:
  run:
    shell: bash

jobs:
  build-binaries:
    runs-on: ubuntu-20.04
    if: github.repository == 'argoproj-labs/argocd-extension-metrics'
    name: Build binaries
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3.1.0
        with:
          go-version: 1.18

      - name: Build binaries
        run: |
          make build
          chmod -R +x dist
      - name: store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: dist 
  build-push-image:
    name: Build & Push
    needs: [ build-binaries ]
    runs-on: ubuntu-20.04
    if: github.repository == 'argoproj-labs/argocd-extension-metrics'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: dist/

      - name: Registry Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}

      - name: set Version
        id: version
        run: |
          tag=$(basename $GITHUB_REF)
          if [ $tag = "main" ]; then
            tag="latest"
          fi
          echo "::set-output name=VERSION::$tag"
      - name: Container build and push with arm64/amd64
        run: |
          IMAGE_NAMESPACE=maheshopsmx VERSION=${{ steps.version.outputs.VERSION }} DOCKER_PUSH=true make image

